HTTPS Updates #1
rooseveltframework/generator-roosevelt pull request #422
Opened 2022-04-29 14:57 UTC by RailonA

Generator-Roosevelt creates a sample application that runs on HTTPS.

2022-04-29 15:03 UTC, kethinov requested changes

2022-04-29 15:03 UTC, kethinov commented on generators/app/promptingHelpers.js
> +// }
why remove this?

if it's not useful / not used, we should just delete it, not comment it out

2022-04-29 15:03 UTC, kethinov commented on generators/app/templates/mvc/models/teddy/homepage.js
> +  model.content.hello = 'HTTPS CHANGES'
revert this

2022-04-29 15:06 UTC, kethinov requested changes

2022-04-29 15:06 UTC, kethinov commented on generators/app/index.js
> +const selfsigned = require('selfsigned');
this needs to be added to package.json and you need to commit a fresh package-lock

2022-04-29 15:07 UTC, kethinov requested changes

2022-04-29 15:43 UTC, kethinov requested changes

2022-04-29 15:43 UTC, kethinov commented on package.json
> +    "selfsigned": "^2.0.1",
```suggestion
    "selfsigned": "~2.0.1",
```

2022-04-29 15:43 UTC, kethinov commented on package.json
> +    "selfsigned": "^2.0.1",
also make sure to run `standard --fix` before committing, not sure this will pass the linter

2022-04-29 16:45 UTC, kethinov commented on package.json
> +    "selfsigned": "^2.0.1",
don't forget to merge the suggestion i put above

some more things to do:

alter this:

```
To run the app:
- Install dependencies: npm i
- To run in dev mode:   npm run dev
- To run in prod mode:  npm run prod
Once running, visit http://localhost:10709
```

The link should include the HTTPS link, not the HTTP link.

also the HTTP server should be disabled. Make it just HTTPS.

and randomize the port of the HTTPS server so it's not always 43733. there is an example of how to do a random port in the HTTP code. just reuse that

2022-04-29 16:46 UTC, kethinov requested changes

2022-04-29 16:46 UTC, kethinov commented on generators/app/index.js
> -  spa () {
pretty sure you deleted way more code here than you should have

we very much intend to continue supporting the SPA feature

you should test it to ensure it still works

2022-04-29 18:49 UTC, Autre31415 commented on generators/app/index.js
> -    this.option('install-deps', {
Why are these options being deleted?

2022-05-02 21:12 UTC, kethinov approved these changes

2022-05-02 21:12 UTC, merged